INSERT INTO Customers(cust_id,
					  cust_contact,
					  cust_email,
					  cust_name,
					  cust_address,
					  cust_city,
					  cust_state,
					  cust_zip)
VALUES (1000000006,
	   NULL,
	   NULL,
	   'Toy Land',
	   '123 Any Street',
	   'New York',
	   'NY',
	   '11111')